"""
Activities Interface
"""
from typing import Any, Protocol

class IActivitiesService(Protocol):
    
    def activity_index(self, self, **kwargs) -> Any:
        ...
    
    def activity_create(self, self, **kwargs) -> Any:
        ...
    
    def activity_destroy(self, self, **kwargs) -> Any:
        ...
    
    def activity_show(self, self, **kwargs) -> Any:
        ...
    
    def activity_update(self, self, **kwargs) -> Any:
        ...
    
    def activitydescription_index(self, self, **kwargs) -> Any:
        ...
    
    def activitydescription_create(self, self, **kwargs) -> Any:
        ...
    
    def activitydescription_destroy(self, self, **kwargs) -> Any:
        ...
    
    def activitydescription_show(self, self, **kwargs) -> Any:
        ...
    
    def activitydescription_update(self, self, **kwargs) -> Any:
        ...
    
    def activityrate_index(self, self, **kwargs) -> Any:
        ...
    
    def activityrate_create(self, self, **kwargs) -> Any:
        ...
    
    def activityrate_destroy(self, self, **kwargs) -> Any:
        ...
    
    def activityrate_show(self, self, **kwargs) -> Any:
        ...
    
    def activityrate_update(self, self, **kwargs) -> Any:
        ...
    
    def expensecategory_index(self, self, **kwargs) -> Any:
        ...
    
    def expensecategory_create(self, self, **kwargs) -> Any:
        ...
    
    def expensecategory_destroy(self, self, **kwargs) -> Any:
        ...
    
    def expensecategory_show(self, self, **kwargs) -> Any:
        ...
    
    def expensecategory_update(self, self, **kwargs) -> Any:
        ...
    
    def laukexpensecategory_index(self, self, **kwargs) -> Any:
        ...
    
    def timer_destroy(self, self, **kwargs) -> Any:
        ...
    
    def timer_show(self, self, **kwargs) -> Any:
        ...
    
    def timer_create(self, self, **kwargs) -> Any:
        ...
    
    def utbmscode_index(self, self, **kwargs) -> Any:
        ...
    
    def utbmscode_show(self, self, **kwargs) -> Any:
        ...
    
    def utbmsset_index(self, self, **kwargs) -> Any:
        ...
    