"""
Documents Interface
"""
from typing import Any, Protocol

class IDocumentsService(Protocol):
    
    def document_index(self, self, **kwargs) -> Any:
        ...
    
    def document_create(self, self, **kwargs) -> Any:
        ...
    
    def document_destroy(self, self, **kwargs) -> Any:
        ...
    
    def document_show(self, self, **kwargs) -> Any:
        ...
    
    def document_update(self, self, **kwargs) -> Any:
        ...
    
    def document_copy(self, self, **kwargs) -> Any:
        ...
    
    def document_download(self, self, **kwargs) -> Any:
        ...
    
    def documentversion_index(self, self, **kwargs) -> Any:
        ...
    
    def folder_index(self, self, **kwargs) -> Any:
        ...
    
    def folder_create(self, self, **kwargs) -> Any:
        ...
    
    def folder_list(self, self, **kwargs) -> Any:
        ...
    
    def folder_destroy(self, self, **kwargs) -> Any:
        ...
    
    def folder_show(self, self, **kwargs) -> Any:
        ...
    
    def folder_update(self, self, **kwargs) -> Any:
        ...
    
    def documentarchive_create(self, self, **kwargs) -> Any:
        ...
    
    def documentarchive_show(self, self, **kwargs) -> Any:
        ...
    
    def documentarchive_download(self, self, **kwargs) -> Any:
        ...
    
    def documentautomation_index(self, self, **kwargs) -> Any:
        ...
    
    def documentautomation_create(self, self, **kwargs) -> Any:
        ...
    
    def documentautomation_show(self, self, **kwargs) -> Any:
        ...
    
    def documentcategory_index(self, self, **kwargs) -> Any:
        ...
    
    def documentcategory_create(self, self, **kwargs) -> Any:
        ...
    
    def documentcategory_destroy(self, self, **kwargs) -> Any:
        ...
    
    def documentcategory_show(self, self, **kwargs) -> Any:
        ...
    
    def documentcategory_update(self, self, **kwargs) -> Any:
        ...
    
    def documenttemplate_index(self, self, **kwargs) -> Any:
        ...
    
    def documenttemplate_create(self, self, **kwargs) -> Any:
        ...
    
    def documenttemplate_destroy(self, self, **kwargs) -> Any:
        ...
    
    def documenttemplate_show(self, self, **kwargs) -> Any:
        ...
    
    def documenttemplate_update(self, self, **kwargs) -> Any:
        ...
    
    def documenttemplate_download(self, self, **kwargs) -> Any:
        ...
    
    def comment_index(self, self, **kwargs) -> Any:
        ...
    
    def comment_create(self, self, **kwargs) -> Any:
        ...
    
    def comment_destroy(self, self, **kwargs) -> Any:
        ...
    
    def comment_show(self, self, **kwargs) -> Any:
        ...
    
    def comment_update(self, self, **kwargs) -> Any:
        ...
    