"""
Matters Interface
"""
from typing import Any, Protocol

class IMattersService(Protocol):
    
    def matter_index(self, self, **kwargs) -> Any:
        ...
    
    def matter_create(self, self, **kwargs) -> Any:
        ...
    
    def matter_destroy(self, self, **kwargs) -> Any:
        ...
    
    def matter_show(self, self, **kwargs) -> Any:
        ...
    
    def matter_update(self, self, **kwargs) -> Any:
        ...
    
    def relationship_index(self, self, **kwargs) -> Any:
        ...
    
    def relationship_create(self, self, **kwargs) -> Any:
        ...
    
    def relationship_destroy(self, self, **kwargs) -> Any:
        ...
    
    def relationship_show(self, self, **kwargs) -> Any:
        ...
    
    def relationship_update(self, self, **kwargs) -> Any:
        ...
    
    def client_show(self, self, **kwargs) -> Any:
        ...
    
    def relatedcontacts_index(self, self, **kwargs) -> Any:
        ...
    
    def mattercontacts_index(self, self, **kwargs) -> Any:
        ...
    
    def note_index(self, self, **kwargs) -> Any:
        ...
    
    def note_create(self, self, **kwargs) -> Any:
        ...
    
    def note_destroy(self, self, **kwargs) -> Any:
        ...
    
    def note_show(self, self, **kwargs) -> Any:
        ...
    
    def note_update(self, self, **kwargs) -> Any:
        ...
    
    def practicearea_index(self, self, **kwargs) -> Any:
        ...
    
    def practicearea_create(self, self, **kwargs) -> Any:
        ...
    
    def practicearea_destroy(self, self, **kwargs) -> Any:
        ...
    
    def practicearea_show(self, self, **kwargs) -> Any:
        ...
    
    def practicearea_update(self, self, **kwargs) -> Any:
        ...
    
    def logentry_index(self, self, **kwargs) -> Any:
        ...
    
    def matterstage_index(self, self, **kwargs) -> Any:
        ...
    
    def medicalrecordsrequest_index(self, self, **kwargs) -> Any:
        ...
    
    def medicalrecordsrequest_create(self, self, **kwargs) -> Any:
        ...
    
    def medicalrecordsrequest_destroy(self, self, **kwargs) -> Any:
        ...
    
    def medicalrecordsrequest_show(self, self, **kwargs) -> Any:
        ...
    
    def medicalrecordsrequest_update(self, self, **kwargs) -> Any:
        ...
    
    def medicalrecord_destroy(self, self, **kwargs) -> Any:
        ...
    
    def medicalrecord_update(self, self, **kwargs) -> Any:
        ...
    
    def medicalbill_destroy(self, self, **kwargs) -> Any:
        ...
    
    def medicalbill_update(self, self, **kwargs) -> Any:
        ...
    
    def damage_index(self, self, **kwargs) -> Any:
        ...
    
    def damage_create(self, self, **kwargs) -> Any:
        ...
    
    def damage_destroy(self, self, **kwargs) -> Any:
        ...
    
    def damage_show(self, self, **kwargs) -> Any:
        ...
    
    def damage_update(self, self, **kwargs) -> Any:
        ...
    