openapi: 3.0.3
info:
  title: Custom Fields API
  version: "1.0"
paths:
  /custom_fields/templates:
    get:
      tags: [CustomFields]
      operationId: listFieldTemplates
      summary: List custom field templates
      responses:
        "200":
          description: List of templates
  /matters/{id}/custom_fields:
    get:
      tags: [CustomFields]
      operationId: getMatterCustomFields
      summary: Get custom fields for a matter
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Custom field values
    post:
      tags: [CustomFields]
      operationId: setMatterCustomFields
      summary: Set custom fields for a matter
      requestBody:
        content:
          application/json:
            schema:
              type: object
              additionalProperties: true
      responses:
        "200":
          description: Updated